services:
 portainer:
    image: portainer/portainer-ce:2.20.3
    container_name: ${PORTAINER_CONTAINER_NAME:-Porto}
    restart: always
    # environment:
    #   - PORTAINER_TEMPLATE_FORMAT=v3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_LOCAL_DATA_PATH:-./data}:/data
      # ./data is the persistent bind mount for configuration & custom templates
    ports:
      - ${PORTAINER_UI_PORT:-9000}:9000
      - ${PORTAINER_UI_SECURE_PORT:-9433}:9443
      - ${PORTAINER_AGENT_PORT:-8000}:8000

# To run: clone to folder and run `docker compose up -d` with defaults or create a .env file with alternative parameters
# UI: http://localhost:9000

# Backup: To backup Portainer config: Use the "Backup up Portainer" section under
#   "Settings" at http://localhost:9000/#!/settings

# Restore: To restore Portainer config from backup: Stop & delete the running portainer
#   container. Next, extract the entire contents of the backup .tar file into a new
#   ./data folder (bind mount). Start the service `docker compose up -d`

# Old Portainer App Templates url: https://raw.githubusercontent.com/portainer/templates/master/templates-2.0.json

# Roadmap:
# ~. Ongoing: add various docker configurations 
# 1. Cloudflare Tunnel setup for running fully qualified domain names
# 2. Cloudflare or other DNS management UI
# 3. Backup & restore manager for container data
# 4. CI/CD integration for live deployment
# 5. Fork Portainer main branch to remove ads and add back features removed from paid versions
