services:
  web:
    image: php:${VERSION:-latest}
    container_name: ${CONTAINER_NAME:-PHP}
    restart: ${RESTART:-always}
    environment:
      PHP_EXTENSIONS: ${PHP_EXTENSIONS:-}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-}
    ports:
      - "${PORT:-8081}:80"
    volumes:
      - ${PHP_WEB_ROOT:-./app}:/var/www/html
