services:
  web:
    image: php:${VERSION:-latest}
    container_name: ${CONTAINER_NAME:-PHP}
    restart: ${RESTART:-always}
    environment:
      PHP_EXTENSIONS: ${PHP_EXTENSIONS:-}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-}
      APACHE_SERVER_NAME: ${APACHE_SERVER_NAME:-localhost}
    ports:
      - "${PORT:-8081}:80"
    volumes:
      - ${PHP_WEB_ROOT:-./app}:/var/www/html
    command: >
      /bin/bash -c "
      if [[ -n '$$PHP_EXTENSIONS' ]]; then
        docker-php-ext-install $$PHP_EXTENSIONS || { 
          echo 'Error installing PHP extensions via docker-php-ext-install $$PHP_EXTENSIONS ($PHP_EXTENSIONS) - check your docker-compose.yml command: section'; 
          exit 1; 
        }
      fi &&
      if ! grep -q 'ServerName' /etc/apache2/apache2.conf; then
        echo 'ServerName $$APACHE_SERVER_NAME' >> /etc/apache2/apache2.conf;
      else
        sed -i 's/^ServerName .*/ServerName $$APACHE_SERVER_NAME/' /etc/apache2/apache2.conf;
      fi &&
      apache2-foreground"
