services:
  db:
    container_name: ${CONTAINER_NAME:-mariadb}
    image: mariadb:${MYSQL_VERSION:-latest}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MOUNT_ROOT: ${MOUNT_ROOT:-}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ${MOUNT_ROOT:-/var/lib/portainer}/${CONTAINER_NAME:-mariadb}/data:/var/lib/mariadb
    command: >
      /bin/bash -c "
      if [ ! -f /docker-entrypoint-initdb.d/init.sql ]; then
        MYSQL_DATABASE_TRIMMED=\$$(echo \"${MYSQL_DATABASE}\" | tr -s ' ' | xargs); # trim & normalize spaces:
        MYSQL_DATABASE_TRIMMED=\$$(echo \"${MYSQL_DATABASE_TRIMMED}\" | sed '/^.*,/!s/ /, /g'); # insert commas if there are none separating dbs
        IFS=' ' read -ra ADDR <<< $${MYSQL_DATABASE_TRIMMED};
        for i in \"\$${ADDR[@]}\"; do # create all databases (separated by spaces in .env - not supported by mysql 5.7):
          echo \"CREATE DATABASE IF NOT EXISTS \$${i}; GRANT ALL PRIVILEGES ON \\\`\$${i}\\\`.* TO '\$${MYSQL_USER}'@'%' WITH GRANT OPTION;\" >> /docker-entrypoint-initdb.d/init.sql; 
        done;
        echo \"GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO '\$${MYSQL_USER}'@'%' WITH GRANT OPTION;\" >> /docker-entrypoint-initdb.d/init.sql; 
        if [[ \$${MYSQL_DATABASE_TRIMMED} =~ ' ' ]] && [[ \$${#ADDR[@]} -gt 1 ]]; then # remove incorrectly generated database name with spaces
          echo \"DROP DATABASE IF EXISTS \\\`\$${MYSQL_DATABASE_TRIMMED}\\\`;\" >> /docker-entrypoint-initdb.d/init.sql;
          MYSQL_DATABASE_TRIMMED=\$$(echo "\$${MYSQL_DATABASE_TRIMMED}" | sed 's/_/\\\\_/g'); # escape any underscores for the privilege table
          echo \"REVOKE ALL PRIVILEGES ON \\\`\$${MYSQL_DATABASE_TRIMMED}\\\`.* FROM '\$${MYSQL_USER}'@'%';\" >> /docker-entrypoint-initdb.d/init.sql;
          echo \"FLUSH PRIVILEGES;\" >> /docker-entrypoint-initdb.d/init.sql;
        fi;
      fi;
      exec /usr/local/bin/docker-entrypoint.sh mariadbd $${MYSQLD_PARAMETERS:-}"
