services:
  web:
    image: trafex/php-nginx:${VERSION:-latest}
    container_name: ${CONTAINER_NAME:-PHP}
    restart: ${RESTART:-always}
    # ports:
    #   - "${TRAFEX_PORT:-8080}:8080"
    volumes:
      - ${PHP_WEB_ROOT:-./app}:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CONTAINER_NAME:-nginx-hello}.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.${CONTAINER_NAME:-nginx-hello}.entrypoints=web,websecure"
      - "traefik.http.routers.${CONTAINER_NAME:-nginx-hello}.tls=true"
      - "traefik.http.routers.${CONTAINER_NAME:-nginx-hello}.tls.certresolver=production"
    networks:
      - traefik

networks:
  traefik:
    external: true

# NOTE: =====CLOUDFLARE=====: You will need to TEMPORARILY DISABLE SSL/TLS AND the https upgrade
#       in ../traefik/config/traefik.yml in order to pass the ACME challenge. Review the log file
#       ../traefik/config/logs/traefik/traefik.log to determine success. After the LetsEncrpt cert
#       has been issued, you will get TOO MANY REDIRECTS (https) AND 404 Not Found (http) until
#       you re-enable SSL/TLS. For Cloudflare setups, you don't need to use the traefik.yml https
#       redirect - instead use the setting in the "Edge Certificates" subsection under "SSL/TLS"
#       *ALSO* You don't need to disable proxying the origin server IP at any time (leave on).
#
#       ======GODADDY======: No additional configuration needed as godaddy does not handle edge
#       certificates - you can use the traefik.yml https redirect but should note that this would
#       potentially break the ACME challenge for new domains that use Cloudflare. Redirecting in
#       the application layer is preferred.