name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Assuming 'collate.sh' is your script that generates 'templates.json'
      - name: Run Collate Script
        run: ./collate.sh

      # Create a directory named 'latest' and move 'templates.json' into it
      - name: Prepare for Deployment
        run: |
          mkdir -p latest
          mv templates.json latest/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./latest
