name: Build and Deploy to GitHub Pages (not yet working, has to be tested live)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Collate Templates & Package for Deployment
        run: |
          ./collate.sh
          mkdir -p latest
          mv templates.json latest/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # Ensure this matches your GitHub Pages branch
          publish_dir: ./latest
